import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { createOrder, fetchAllOrders, updateOrder } from "./orderAPI";

const initialState = {
	orders: [],
	status: "idle",
	currentOrder: null,
	totalOrders: 0,
};

export const createOrderAsync = createAsyncThunk(
	"orders/createOrder",
	async (amount) => {
		const response = await createOrder(amount);

		return response.data;
	}
);
export const updateOrderAsync = createAsyncThunk(
	"orders/updateOrder",
	async (amount) => {
		const response = await updateOrder(amount);

		return response.data;
	}
);
export const fetchAllOrdersAsync = createAsyncThunk(
	"orders/fetchAllOrders",
	async ({ sort, pagination }) => {
		const response = await fetchAllOrders({ sort, pagination });
		return response.data;
	}
);
export const orderSlice = createSlice({
	name: "orders",
	initialState,
	reducers: {
		resetOrder: (state) => {
			state.currentOrder = null;
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(createOrderAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(createOrderAsync.fulfilled, (state, action) => {
				state.status = "idle";
				state.orders.push(action.payload);
				state.currentOrder = action.payload;
			})
			.addCase(fetchAllOrdersAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(fetchAllOrdersAsync.fulfilled, (state, action) => {
				state.status = "idle";
				state.orders = action.payload.orders;
				state.totalOrders = action.payload.totalOrders;
			})
			.addCase(updateOrderAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(updateOrderAsync.fulfilled, (state, action) => {
				state.status = "idle";
				const index = state.orders.findIndex(
					(order) => order.id === action.payload.id
				);
				state.orders[index] = action.payload;
			});
	},
});

export const { resetOrder } = orderSlice.actions;

export const selectCurrentOrder = (state) => state.orders.currentOrder;
export const selectOrders = (state) => state.orders.orders;
export const selectTotalOrders = (state) => state.orders.totalOrders;

export default orderSlice.reducer;
